# Generated by Django 4.2.6 on 2023-11-29 19:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('PROJECT_NAME', models.CharField(max_length=255)),
                ('area', models.CharField(choices=[('Acces', 'Axces'), ('Transversal', 'Transversal'), ('Gestion del Riesgo', 'Gestion del Riesgo'), ('Mercadeo', 'Mercadeo')], max_length=50)),
                ('tipo', models.CharField(choices=[('Fore', 'Fore'), ('Reca', 'Reca')], max_length=4)),
                ('enlace_tw', models.URLField()),
                ('desarrollador', models.CharField(max_length=255)),
                ('funcional', models.CharField(max_length=255)),
                ('fecha_entrega_qa', models.DateField()),
                ('fecha_estimada_liberacion', models.DateField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('actividad', models.CharField(choices=[('Estimacion', 'Estimacion'), ('Diseño', 'Diseño'), ('Ejecucion', 'Ejecucion'), ('Pendiente', 'Pendiente'), ('Finalizado', 'Finalizado')], max_length=50)),
                ('reportado', models.CharField(max_length=255)),
            ],
        ),
    ]
