# Generated by Django 4.2.6 on 2023-12-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_alter_proyecto_reportado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='PROJECT_NAME',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='project_name',
            field=models.CharField(default='Valor predeterminado', max_length=255, unique=True),
        ),
    ]
