# Generated by Django 4.2.6 on 2023-10-24 16:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('FECHA', models.DateField()),
                ('STATUS', models.CharField(choices=[('pendiente', 'Pendiente'), ('finalizado', 'Finalizado')], default='pendiente', max_length=10)),
                ('PROJECT_NAME', models.CharField(max_length=255)),
                ('BUG', models.TextField()),
                ('AREA', models.CharField(choices=[('axces', 'AXCES'), ('gestion del riesgo', 'Gestion Del Riesgo'), ('mercadeo', 'Mercadeo'), ('transversal', 'Transversal')], max_length=20)),
                ('CAUSAL', models.CharField(choices=[('desarrollo', 'Desarrollo'), ('analisis', 'Analisis'), ('documentacion', 'Documentacion'), ('testing', 'Testing'), ('diseño', 'Diseño')], max_length=20)),
                ('SEVERIDAD', models.CharField(choices=[('funcional', 'Funcional'), ('presentacion', 'Presentacion'), ('bloqueante', 'Bloqueante')], max_length=20)),
                ('ENLACE', models.URLField()),
                ('ENCARGADO', models.CharField(max_length=255)),
            ],
        ),
    ]
