# Generated by Django 4.2.6 on 2023-12-03 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_alter_proyecto_area'),
        ('report_bug', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='AREA',
            field=models.CharField(choices=[('Axces', 'Axces'), ('Transversal', 'Transversal'), ('Gestion del Riesgo', 'Gestion del Riesgo'), ('Mercadeo', 'Mercadeo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='CAUSAL',
            field=models.CharField(choices=[('Desarrollo', 'Desarrollo'), ('Analisis', 'Analisis'), ('Documentacion', 'Documentacion'), ('Testing', 'Testing'), ('Diseño', 'Diseño')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='PROJECT_NAME',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto'),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='SEVERIDAD',
            field=models.CharField(choices=[('Funcional', 'Funcional'), ('Presentacion', 'Presentacion'), ('Bloqueante', 'Bloqueante')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='STATUS',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Finalizado', 'Finalizado')], default='pendiente', max_length=10),
        ),
    ]
