# Generated by Django 4.2.6 on 2023-12-03 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_bug', '0003_alter_bugreport_area_alter_bugreport_causal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugreport',
            name='PROJECT_NAME',
        ),
    ]
