# Generated by Django 4.2.6 on 2023-12-03 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_alter_proyecto_area'),
        ('report_bug', '0004_remove_bugreport_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='PROJECT_NAME',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto'),
            preserve_default=False,
        ),
    ]
