# Generated by Django 4.2.6 on 2023-12-01 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos', '0004_alter_proyecto_actividad_alter_proyecto_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimacionProyecto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('est_diseno_cp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('est_eje_cp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('eje_diseno', models.DecimalField(decimal_places=2, max_digits=5)),
                ('eje_cp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_estimacion', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
                ('reportado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimaciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
